export const REDIRECT = 'REDIRECT'

export const SEARCH_DONE = 'SEARCH_DONE'
export const VIDEO_STATUS = 'VIDEO_STATUS'

export const STREAM_RECEIVE = 'STREAM_RECEIVE'
export const STREAM_SEND = 'STREAM_SEND'

export const CONTROL_SEND_PLAY = 'CONTROL_SEND_PLAY'
export const CONTROL_SEND_PAUSE = 'CONTROL_SEND_PAUSE'
export const CONTROL_SEND_JUMP = 'CONTROL_SEND_JUMP'

export const PEER_READY = 'PEER_READY'
export const PEER_CONNECT = 'PEER_CONNECT'
export const PEER_CONNECT_FAIL = 'PEER_CONNECT_FAIL'
export const PEER_CONNECTED = 'PEER_CONNECTED'
export const PEER_RECEIVE_CONNECTION = 'PEER_RECEIVE_CONNECTION'
export const PEER_REQUEST_SYNC = 'PEER_REQUEST_SYNC'
export const PEER_SEND_SYNC = 'PEER_SEND_SYNC'
