export const SEARCH_DONE = 'SEARCH_DONE'

export const STREAM_RECEIVE = 'STREAM_RECEIVE'
export const STREAM_SEND = 'STREAM_SEND'

export const CONTROL_SEND_PLAY = 'CONTROL_SEND_PLAY'
export const CONTROL_SEND_PAUSE = 'CONTROL_SEND_PAUSE'
export const CONTROL_SEND_JUMP = 'CONTROL_SEND_JUMP'

export const PEER_READY = 'PEER_READY'
export const PEER_CONNECT = 'PEER_CONNECT'
export const PEER_RECEIVE_CONNECTION = 'PEER_RECEIVE_CONNECTION'
